### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by adindravickarega** [cluangar/YOLOv5-RK3588-Python#1]
~/YOLOv5-RK3588-Python$ python inference_npu.py
--> Load RKNN model
done
--> Init runtime environment
I RKNN: [05:23:26.718] RKNN Runtime Information: librknnrt version: 1.4.0 (a10f100eb@2022-09-09T09:07:14)
I RKNN: [05:23:26.719] RKNN Driver Information: version: 0.8.8
I RKNN: [05:23:26.719] RKNN Model Information: version: 1, toolkit version: 1.2.6-source_code(compiler version: 1.2.6b3 (4b29ee34e@2022-04-24T05:04:45)), target: RKNPU v2, target platform: rk3588, framework name: ONNX, framework layout: NCHW
done
E Catch exception when setting inputs.
E Traceback (most recent call last):
  File "/home/orangepi/.local/lib/python3.10/site-packages/rknnlite/api/rknn_lite.py", line 200, in inference
    self.rknn_runtime.set_inputs(inputs, data_type, data_format, inputs_pass_through=inputs_pass_through)
  File "rknnlite/api/rknn_runtime.py", line 1067, in rknnlite.api.rknn_runtime.RKNNRuntime.set_inputs
Exception: The input[0] need 4dims input, but 3dims input buffer feed.

Traceback (most recent call last):
  File "/home/orangepi/YOLOv5-RK3588-Python/inference_npu.py", line 212, in <module>
    input0_data = outputs[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by Anton231200** [comment]
were you able to solve this problem?

**Comment by cluangar** [comment]
My code test on python3.9 and use rknn_toolkit_lite2-1.4.0-cp39-cp39m-linux_aarch64.whl

**Comment by rebolomo** [comment]
add "frame = np.expand_dims(frame, 0)" after letterbox function to fix this problem.
